[profile.default]
remappings = [
    "@openzeppelin=contracts/lib/openzeppelin-contracts/",
    "@chainlink/contracts=contracts/lib/chainlink-brownie-contracts/contracts/",
    "@lido-dao/contracts=contracts/lib/lido-dao/contracts/",
    "@solmate=contracts/lib/solmate/src/",
]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib', 'contracts/lib/openzeppelin-contracts/contracts']
cache_path = 'contracts/cache'
auto_detect_remappings = true
gas_reports = ["RafflePool"]
fs_permissions = [{ access = "read-write", path = "./"}]
# solc = '0.8.20'

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

# Fuzz run options - adjust as needed for your fuzzing campaign
[fuzz]
runs = 1000               # the number of fuzz runs for tests
max_local_rejects = 66000 # max number of individual inputs that may be rejected before the test aborts
max_test_rejects = 1      # max number of tests that may be rejected before the test aborts      


[fmt]
# `forge fmt` defaults with line_length reduced from 120 to 80
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = 'long'
multiline_func_header = 'attributes_first'
quote_style = 'double'
number_underscore = 'preserve'
single_line_statement_blocks = 'preserve'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config


[doc]
title = 'StakeWell Documentation'
