// Generated by @wagmi/cli@1.3.0 on 8/14/2023 at 3:47:44 PM
import {
  useContractRead,
  UseContractReadConfig,
  useContractWrite,
  UseContractWriteConfig,
  usePrepareContractWrite,
  UsePrepareContractWriteConfig,
  useContractEvent,
  UseContractEventConfig,
  Address,
} from 'wagmi'
import {
  ReadContractResult,
  WriteContractMode,
  PrepareWriteContractResult,
} from 'wagmi/actions'

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IERC20
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ierc20ABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// StakePool
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export const stakePoolABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [{ name: '_stETH', internalType: 'address', type: 'address' }],
  },
  { type: 'error', inputs: [], name: 'StakePool__InsufficientStETHBalance' },
  { type: 'error', inputs: [], name: 'StakePool__MintFailed' },
  { type: 'error', inputs: [], name: 'StakePool__NeedsMoreThanZero' },
  { type: 'error', inputs: [], name: 'StakePool__TransferFailed' },
  { type: 'error', inputs: [], name: 'StakePool__WithdrawalFailed' },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'MintAndStakeDeposited',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'StakeDeposited',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'StakeDepositedWithPermit',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'amount',
        internalType: 'uint256',
        type: 'uint256',
        indexed: true,
      },
    ],
    name: 'StakeWithdrawn',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'user', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [],
    name: 'depositEth',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'amountStEth', internalType: 'uint256', type: 'uint256' }],
    name: 'depositStEth',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'amountStEth', internalType: 'uint256', type: 'uint256' },
      { name: 'deadline', internalType: 'uint256', type: 'uint256' },
      { name: 'v', internalType: 'uint8', type: 'uint8' },
      { name: 'r', internalType: 'bytes32', type: 'bytes32' },
      { name: 's', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'depositStEthWithPermit',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'i_stETH',
    outputs: [
      { name: '', internalType: 'contract IERC20Permit', type: 'address' },
    ],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 's_stakingRewardsTotal',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 's_totalUserDeposits',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalBalance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalUserDeposits',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256' }],
    name: 'withdrawEth',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'amount', internalType: 'uint256', type: 'uint256' }],
    name: 'withdrawStEth',
    outputs: [],
  },
] as const

/**
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export const stakePoolAddress = {
  5: '0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A',
} as const

/**
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export const stakePoolConfig = {
  address: stakePoolAddress,
  abi: stakePoolABI,
} as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// IERC20Permit
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const ierc20PermitABI = [
  {
    type: 'event',
    anonymous: false,
    inputs: [
      {
        name: 'owner',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'spender',
        internalType: 'address',
        type: 'address',
        indexed: true,
      },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Approval',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'from', internalType: 'address', type: 'address', indexed: true },
      { name: 'to', internalType: 'address', type: 'address', indexed: true },
      {
        name: 'value',
        internalType: 'uint256',
        type: 'uint256',
        indexed: false,
      },
    ],
    name: 'Transfer',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'DOMAIN_SEPARATOR',
    outputs: [{ name: '', internalType: 'bytes32', type: 'bytes32' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
    ],
    name: 'allowance',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'approve',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'account', internalType: 'address', type: 'address' }],
    name: 'balanceOf',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: 'owner', internalType: 'address', type: 'address' }],
    name: 'nonces',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'owner', internalType: 'address', type: 'address' },
      { name: 'spender', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
      { name: 'deadline', internalType: 'uint256', type: 'uint256' },
      { name: 'v', internalType: 'uint8', type: 'uint8' },
      { name: 'r', internalType: 'bytes32', type: 'bytes32' },
      { name: 's', internalType: 'bytes32', type: 'bytes32' },
    ],
    name: 'permit',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'totalSupply',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'recipient', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transfer',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'sender', internalType: 'address', type: 'address' },
      { name: 'recipient', internalType: 'address', type: 'address' },
      { name: 'amount', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'transferFrom',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
] as const

//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// React
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20ABI}__.
 */
export function useIerc20Read<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof ierc20ABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20ABI, TFunctionName, TSelectData>,
    'abi'
  > = {} as any,
) {
  return useContractRead({ abi: ierc20ABI, ...config } as UseContractReadConfig<
    typeof ierc20ABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20ABI}__ and `functionName` set to `"allowance"`.
 */
export function useIerc20Allowance<
  TFunctionName extends 'allowance',
  TSelectData = ReadContractResult<typeof ierc20ABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20ABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: ierc20ABI,
    functionName: 'allowance',
    ...config,
  } as UseContractReadConfig<typeof ierc20ABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20ABI}__ and `functionName` set to `"balanceOf"`.
 */
export function useIerc20BalanceOf<
  TFunctionName extends 'balanceOf',
  TSelectData = ReadContractResult<typeof ierc20ABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20ABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: ierc20ABI,
    functionName: 'balanceOf',
    ...config,
  } as UseContractReadConfig<typeof ierc20ABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20ABI}__ and `functionName` set to `"totalSupply"`.
 */
export function useIerc20TotalSupply<
  TFunctionName extends 'totalSupply',
  TSelectData = ReadContractResult<typeof ierc20ABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20ABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: ierc20ABI,
    functionName: 'totalSupply',
    ...config,
  } as UseContractReadConfig<typeof ierc20ABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ierc20ABI}__.
 */
export function useIerc20Write<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<typeof ierc20ABI, string>['request']['abi'],
        TFunctionName,
        TMode
      >
    : UseContractWriteConfig<typeof ierc20ABI, TFunctionName, TMode> & {
        abi?: never
      } = {} as any,
) {
  return useContractWrite<typeof ierc20ABI, TFunctionName, TMode>({
    abi: ierc20ABI,
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ierc20ABI}__ and `functionName` set to `"approve"`.
 */
export function useIerc20Approve<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof ierc20ABI,
          'approve'
        >['request']['abi'],
        'approve',
        TMode
      > & { functionName?: 'approve' }
    : UseContractWriteConfig<typeof ierc20ABI, 'approve', TMode> & {
        abi?: never
        functionName?: 'approve'
      } = {} as any,
) {
  return useContractWrite<typeof ierc20ABI, 'approve', TMode>({
    abi: ierc20ABI,
    functionName: 'approve',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ierc20ABI}__ and `functionName` set to `"transfer"`.
 */
export function useIerc20Transfer<TMode extends WriteContractMode = undefined>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof ierc20ABI,
          'transfer'
        >['request']['abi'],
        'transfer',
        TMode
      > & { functionName?: 'transfer' }
    : UseContractWriteConfig<typeof ierc20ABI, 'transfer', TMode> & {
        abi?: never
        functionName?: 'transfer'
      } = {} as any,
) {
  return useContractWrite<typeof ierc20ABI, 'transfer', TMode>({
    abi: ierc20ABI,
    functionName: 'transfer',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ierc20ABI}__ and `functionName` set to `"transferFrom"`.
 */
export function useIerc20TransferFrom<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof ierc20ABI,
          'transferFrom'
        >['request']['abi'],
        'transferFrom',
        TMode
      > & { functionName?: 'transferFrom' }
    : UseContractWriteConfig<typeof ierc20ABI, 'transferFrom', TMode> & {
        abi?: never
        functionName?: 'transferFrom'
      } = {} as any,
) {
  return useContractWrite<typeof ierc20ABI, 'transferFrom', TMode>({
    abi: ierc20ABI,
    functionName: 'transferFrom',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ierc20ABI}__.
 */
export function usePrepareIerc20Write<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ierc20ABI, TFunctionName>,
    'abi'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: ierc20ABI,
    ...config,
  } as UsePrepareContractWriteConfig<typeof ierc20ABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ierc20ABI}__ and `functionName` set to `"approve"`.
 */
export function usePrepareIerc20Approve(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ierc20ABI, 'approve'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: ierc20ABI,
    functionName: 'approve',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ierc20ABI, 'approve'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ierc20ABI}__ and `functionName` set to `"transfer"`.
 */
export function usePrepareIerc20Transfer(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ierc20ABI, 'transfer'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: ierc20ABI,
    functionName: 'transfer',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ierc20ABI, 'transfer'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ierc20ABI}__ and `functionName` set to `"transferFrom"`.
 */
export function usePrepareIerc20TransferFrom(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ierc20ABI, 'transferFrom'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: ierc20ABI,
    functionName: 'transferFrom',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ierc20ABI, 'transferFrom'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ierc20ABI}__.
 */
export function useIerc20Event<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof ierc20ABI, TEventName>,
    'abi'
  > = {} as any,
) {
  return useContractEvent({
    abi: ierc20ABI,
    ...config,
  } as UseContractEventConfig<typeof ierc20ABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ierc20ABI}__ and `eventName` set to `"Approval"`.
 */
export function useIerc20ApprovalEvent(
  config: Omit<
    UseContractEventConfig<typeof ierc20ABI, 'Approval'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: ierc20ABI,
    eventName: 'Approval',
    ...config,
  } as UseContractEventConfig<typeof ierc20ABI, 'Approval'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ierc20ABI}__ and `eventName` set to `"Transfer"`.
 */
export function useIerc20TransferEvent(
  config: Omit<
    UseContractEventConfig<typeof ierc20ABI, 'Transfer'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: ierc20ABI,
    eventName: 'Transfer',
    ...config,
  } as UseContractEventConfig<typeof ierc20ABI, 'Transfer'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link stakePoolABI}__.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof stakePoolABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>,
    'abi' | 'address'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractRead({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    ...config,
  } as UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"balanceOf"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolBalanceOf<
  TFunctionName extends 'balanceOf',
  TSelectData = ReadContractResult<typeof stakePoolABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractRead({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'balanceOf',
    ...config,
  } as UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"i_stETH"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolIStEth<
  TFunctionName extends 'i_stETH',
  TSelectData = ReadContractResult<typeof stakePoolABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractRead({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'i_stETH',
    ...config,
  } as UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"s_stakingRewardsTotal"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolSStakingRewardsTotal<
  TFunctionName extends 's_stakingRewardsTotal',
  TSelectData = ReadContractResult<typeof stakePoolABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractRead({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 's_stakingRewardsTotal',
    ...config,
  } as UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"s_totalUserDeposits"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolSTotalUserDeposits<
  TFunctionName extends 's_totalUserDeposits',
  TSelectData = ReadContractResult<typeof stakePoolABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractRead({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 's_totalUserDeposits',
    ...config,
  } as UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"totalBalance"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolTotalBalance<
  TFunctionName extends 'totalBalance',
  TSelectData = ReadContractResult<typeof stakePoolABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractRead({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'totalBalance',
    ...config,
  } as UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"totalUserDeposits"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolTotalUserDeposits<
  TFunctionName extends 'totalUserDeposits',
  TSelectData = ReadContractResult<typeof stakePoolABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractRead({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'totalUserDeposits',
    ...config,
  } as UseContractReadConfig<typeof stakePoolABI, TFunctionName, TSelectData>)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link stakePoolABI}__.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined,
  TChainId extends number = keyof typeof stakePoolAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof stakePoolABI,
          string
        >['request']['abi'],
        TFunctionName,
        TMode
      > & { address?: Address; chainId?: TChainId }
    : UseContractWriteConfig<typeof stakePoolABI, TFunctionName, TMode> & {
        abi?: never
        address?: never
        chainId?: TChainId
      } = {} as any,
) {
  return useContractWrite<typeof stakePoolABI, TFunctionName, TMode>({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"depositEth"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolDepositEth<
  TMode extends WriteContractMode = undefined,
  TChainId extends number = keyof typeof stakePoolAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof stakePoolABI,
          'depositEth'
        >['request']['abi'],
        'depositEth',
        TMode
      > & { address?: Address; chainId?: TChainId; functionName?: 'depositEth' }
    : UseContractWriteConfig<typeof stakePoolABI, 'depositEth', TMode> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'depositEth'
      } = {} as any,
) {
  return useContractWrite<typeof stakePoolABI, 'depositEth', TMode>({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'depositEth',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"depositStEth"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolDepositStEth<
  TMode extends WriteContractMode = undefined,
  TChainId extends number = keyof typeof stakePoolAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof stakePoolABI,
          'depositStEth'
        >['request']['abi'],
        'depositStEth',
        TMode
      > & {
        address?: Address
        chainId?: TChainId
        functionName?: 'depositStEth'
      }
    : UseContractWriteConfig<typeof stakePoolABI, 'depositStEth', TMode> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'depositStEth'
      } = {} as any,
) {
  return useContractWrite<typeof stakePoolABI, 'depositStEth', TMode>({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'depositStEth',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"depositStEthWithPermit"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolDepositStEthWithPermit<
  TMode extends WriteContractMode = undefined,
  TChainId extends number = keyof typeof stakePoolAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof stakePoolABI,
          'depositStEthWithPermit'
        >['request']['abi'],
        'depositStEthWithPermit',
        TMode
      > & {
        address?: Address
        chainId?: TChainId
        functionName?: 'depositStEthWithPermit'
      }
    : UseContractWriteConfig<
        typeof stakePoolABI,
        'depositStEthWithPermit',
        TMode
      > & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'depositStEthWithPermit'
      } = {} as any,
) {
  return useContractWrite<typeof stakePoolABI, 'depositStEthWithPermit', TMode>(
    {
      abi: stakePoolABI,
      address: stakePoolAddress[5],
      functionName: 'depositStEthWithPermit',
      ...config,
    } as any,
  )
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"withdrawEth"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolWithdrawEth<
  TMode extends WriteContractMode = undefined,
  TChainId extends number = keyof typeof stakePoolAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof stakePoolABI,
          'withdrawEth'
        >['request']['abi'],
        'withdrawEth',
        TMode
      > & {
        address?: Address
        chainId?: TChainId
        functionName?: 'withdrawEth'
      }
    : UseContractWriteConfig<typeof stakePoolABI, 'withdrawEth', TMode> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'withdrawEth'
      } = {} as any,
) {
  return useContractWrite<typeof stakePoolABI, 'withdrawEth', TMode>({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'withdrawEth',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"withdrawStEth"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolWithdrawStEth<
  TMode extends WriteContractMode = undefined,
  TChainId extends number = keyof typeof stakePoolAddress,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof stakePoolABI,
          'withdrawStEth'
        >['request']['abi'],
        'withdrawStEth',
        TMode
      > & {
        address?: Address
        chainId?: TChainId
        functionName?: 'withdrawStEth'
      }
    : UseContractWriteConfig<typeof stakePoolABI, 'withdrawStEth', TMode> & {
        abi?: never
        address?: never
        chainId?: TChainId
        functionName?: 'withdrawStEth'
      } = {} as any,
) {
  return useContractWrite<typeof stakePoolABI, 'withdrawStEth', TMode>({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'withdrawStEth',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link stakePoolABI}__.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function usePrepareStakePoolWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof stakePoolABI, TFunctionName>,
    'abi' | 'address'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    ...config,
  } as UsePrepareContractWriteConfig<typeof stakePoolABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"depositEth"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function usePrepareStakePoolDepositEth(
  config: Omit<
    UsePrepareContractWriteConfig<typeof stakePoolABI, 'depositEth'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'depositEth',
    ...config,
  } as UsePrepareContractWriteConfig<typeof stakePoolABI, 'depositEth'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"depositStEth"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function usePrepareStakePoolDepositStEth(
  config: Omit<
    UsePrepareContractWriteConfig<typeof stakePoolABI, 'depositStEth'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'depositStEth',
    ...config,
  } as UsePrepareContractWriteConfig<typeof stakePoolABI, 'depositStEth'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"depositStEthWithPermit"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function usePrepareStakePoolDepositStEthWithPermit(
  config: Omit<
    UsePrepareContractWriteConfig<
      typeof stakePoolABI,
      'depositStEthWithPermit'
    >,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'depositStEthWithPermit',
    ...config,
  } as UsePrepareContractWriteConfig<
    typeof stakePoolABI,
    'depositStEthWithPermit'
  >)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"withdrawEth"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function usePrepareStakePoolWithdrawEth(
  config: Omit<
    UsePrepareContractWriteConfig<typeof stakePoolABI, 'withdrawEth'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'withdrawEth',
    ...config,
  } as UsePrepareContractWriteConfig<typeof stakePoolABI, 'withdrawEth'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link stakePoolABI}__ and `functionName` set to `"withdrawStEth"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function usePrepareStakePoolWithdrawStEth(
  config: Omit<
    UsePrepareContractWriteConfig<typeof stakePoolABI, 'withdrawStEth'>,
    'abi' | 'address' | 'functionName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return usePrepareContractWrite({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    functionName: 'withdrawStEth',
    ...config,
  } as UsePrepareContractWriteConfig<typeof stakePoolABI, 'withdrawStEth'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link stakePoolABI}__.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolEvent<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof stakePoolABI, TEventName>,
    'abi' | 'address'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractEvent({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    ...config,
  } as UseContractEventConfig<typeof stakePoolABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link stakePoolABI}__ and `eventName` set to `"MintAndStakeDeposited"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolMintAndStakeDepositedEvent(
  config: Omit<
    UseContractEventConfig<typeof stakePoolABI, 'MintAndStakeDeposited'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractEvent({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    eventName: 'MintAndStakeDeposited',
    ...config,
  } as UseContractEventConfig<typeof stakePoolABI, 'MintAndStakeDeposited'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link stakePoolABI}__ and `eventName` set to `"StakeDeposited"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolStakeDepositedEvent(
  config: Omit<
    UseContractEventConfig<typeof stakePoolABI, 'StakeDeposited'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractEvent({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    eventName: 'StakeDeposited',
    ...config,
  } as UseContractEventConfig<typeof stakePoolABI, 'StakeDeposited'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link stakePoolABI}__ and `eventName` set to `"StakeDepositedWithPermit"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolStakeDepositedWithPermitEvent(
  config: Omit<
    UseContractEventConfig<typeof stakePoolABI, 'StakeDepositedWithPermit'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractEvent({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    eventName: 'StakeDepositedWithPermit',
    ...config,
  } as UseContractEventConfig<typeof stakePoolABI, 'StakeDepositedWithPermit'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link stakePoolABI}__ and `eventName` set to `"StakeWithdrawn"`.
 *
 * [__View Contract on Goerli Etherscan__](https://goerli.etherscan.io/address/0x69E9b9c9756e79bdc6064D3349DC06a9AF95287A)
 */
export function useStakePoolStakeWithdrawnEvent(
  config: Omit<
    UseContractEventConfig<typeof stakePoolABI, 'StakeWithdrawn'>,
    'abi' | 'address' | 'eventName'
  > & { chainId?: keyof typeof stakePoolAddress } = {} as any,
) {
  return useContractEvent({
    abi: stakePoolABI,
    address: stakePoolAddress[5],
    eventName: 'StakeWithdrawn',
    ...config,
  } as UseContractEventConfig<typeof stakePoolABI, 'StakeWithdrawn'>)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20PermitABI}__.
 */
export function useIerc20PermitRead<
  TFunctionName extends string,
  TSelectData = ReadContractResult<typeof ierc20PermitABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20PermitABI, TFunctionName, TSelectData>,
    'abi'
  > = {} as any,
) {
  return useContractRead({
    abi: ierc20PermitABI,
    ...config,
  } as UseContractReadConfig<
    typeof ierc20PermitABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"DOMAIN_SEPARATOR"`.
 */
export function useIerc20PermitDomainSeparator<
  TFunctionName extends 'DOMAIN_SEPARATOR',
  TSelectData = ReadContractResult<typeof ierc20PermitABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20PermitABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: ierc20PermitABI,
    functionName: 'DOMAIN_SEPARATOR',
    ...config,
  } as UseContractReadConfig<
    typeof ierc20PermitABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"allowance"`.
 */
export function useIerc20PermitAllowance<
  TFunctionName extends 'allowance',
  TSelectData = ReadContractResult<typeof ierc20PermitABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20PermitABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: ierc20PermitABI,
    functionName: 'allowance',
    ...config,
  } as UseContractReadConfig<
    typeof ierc20PermitABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"balanceOf"`.
 */
export function useIerc20PermitBalanceOf<
  TFunctionName extends 'balanceOf',
  TSelectData = ReadContractResult<typeof ierc20PermitABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20PermitABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: ierc20PermitABI,
    functionName: 'balanceOf',
    ...config,
  } as UseContractReadConfig<
    typeof ierc20PermitABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"nonces"`.
 */
export function useIerc20PermitNonces<
  TFunctionName extends 'nonces',
  TSelectData = ReadContractResult<typeof ierc20PermitABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20PermitABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: ierc20PermitABI,
    functionName: 'nonces',
    ...config,
  } as UseContractReadConfig<
    typeof ierc20PermitABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractRead}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"totalSupply"`.
 */
export function useIerc20PermitTotalSupply<
  TFunctionName extends 'totalSupply',
  TSelectData = ReadContractResult<typeof ierc20PermitABI, TFunctionName>,
>(
  config: Omit<
    UseContractReadConfig<typeof ierc20PermitABI, TFunctionName, TSelectData>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return useContractRead({
    abi: ierc20PermitABI,
    functionName: 'totalSupply',
    ...config,
  } as UseContractReadConfig<
    typeof ierc20PermitABI,
    TFunctionName,
    TSelectData
  >)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__.
 */
export function useIerc20PermitWrite<
  TFunctionName extends string,
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof ierc20PermitABI,
          string
        >['request']['abi'],
        TFunctionName,
        TMode
      >
    : UseContractWriteConfig<typeof ierc20PermitABI, TFunctionName, TMode> & {
        abi?: never
      } = {} as any,
) {
  return useContractWrite<typeof ierc20PermitABI, TFunctionName, TMode>({
    abi: ierc20PermitABI,
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"approve"`.
 */
export function useIerc20PermitApprove<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof ierc20PermitABI,
          'approve'
        >['request']['abi'],
        'approve',
        TMode
      > & { functionName?: 'approve' }
    : UseContractWriteConfig<typeof ierc20PermitABI, 'approve', TMode> & {
        abi?: never
        functionName?: 'approve'
      } = {} as any,
) {
  return useContractWrite<typeof ierc20PermitABI, 'approve', TMode>({
    abi: ierc20PermitABI,
    functionName: 'approve',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"permit"`.
 */
export function useIerc20PermitPermit<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof ierc20PermitABI,
          'permit'
        >['request']['abi'],
        'permit',
        TMode
      > & { functionName?: 'permit' }
    : UseContractWriteConfig<typeof ierc20PermitABI, 'permit', TMode> & {
        abi?: never
        functionName?: 'permit'
      } = {} as any,
) {
  return useContractWrite<typeof ierc20PermitABI, 'permit', TMode>({
    abi: ierc20PermitABI,
    functionName: 'permit',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"transfer"`.
 */
export function useIerc20PermitTransfer<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof ierc20PermitABI,
          'transfer'
        >['request']['abi'],
        'transfer',
        TMode
      > & { functionName?: 'transfer' }
    : UseContractWriteConfig<typeof ierc20PermitABI, 'transfer', TMode> & {
        abi?: never
        functionName?: 'transfer'
      } = {} as any,
) {
  return useContractWrite<typeof ierc20PermitABI, 'transfer', TMode>({
    abi: ierc20PermitABI,
    functionName: 'transfer',
    ...config,
  } as any)
}

/**
 * Wraps __{@link useContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"transferFrom"`.
 */
export function useIerc20PermitTransferFrom<
  TMode extends WriteContractMode = undefined,
>(
  config: TMode extends 'prepared'
    ? UseContractWriteConfig<
        PrepareWriteContractResult<
          typeof ierc20PermitABI,
          'transferFrom'
        >['request']['abi'],
        'transferFrom',
        TMode
      > & { functionName?: 'transferFrom' }
    : UseContractWriteConfig<typeof ierc20PermitABI, 'transferFrom', TMode> & {
        abi?: never
        functionName?: 'transferFrom'
      } = {} as any,
) {
  return useContractWrite<typeof ierc20PermitABI, 'transferFrom', TMode>({
    abi: ierc20PermitABI,
    functionName: 'transferFrom',
    ...config,
  } as any)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__.
 */
export function usePrepareIerc20PermitWrite<TFunctionName extends string>(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ierc20PermitABI, TFunctionName>,
    'abi'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: ierc20PermitABI,
    ...config,
  } as UsePrepareContractWriteConfig<typeof ierc20PermitABI, TFunctionName>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"approve"`.
 */
export function usePrepareIerc20PermitApprove(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ierc20PermitABI, 'approve'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: ierc20PermitABI,
    functionName: 'approve',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ierc20PermitABI, 'approve'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"permit"`.
 */
export function usePrepareIerc20PermitPermit(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ierc20PermitABI, 'permit'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: ierc20PermitABI,
    functionName: 'permit',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ierc20PermitABI, 'permit'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"transfer"`.
 */
export function usePrepareIerc20PermitTransfer(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ierc20PermitABI, 'transfer'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: ierc20PermitABI,
    functionName: 'transfer',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ierc20PermitABI, 'transfer'>)
}

/**
 * Wraps __{@link usePrepareContractWrite}__ with `abi` set to __{@link ierc20PermitABI}__ and `functionName` set to `"transferFrom"`.
 */
export function usePrepareIerc20PermitTransferFrom(
  config: Omit<
    UsePrepareContractWriteConfig<typeof ierc20PermitABI, 'transferFrom'>,
    'abi' | 'functionName'
  > = {} as any,
) {
  return usePrepareContractWrite({
    abi: ierc20PermitABI,
    functionName: 'transferFrom',
    ...config,
  } as UsePrepareContractWriteConfig<typeof ierc20PermitABI, 'transferFrom'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ierc20PermitABI}__.
 */
export function useIerc20PermitEvent<TEventName extends string>(
  config: Omit<
    UseContractEventConfig<typeof ierc20PermitABI, TEventName>,
    'abi'
  > = {} as any,
) {
  return useContractEvent({
    abi: ierc20PermitABI,
    ...config,
  } as UseContractEventConfig<typeof ierc20PermitABI, TEventName>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ierc20PermitABI}__ and `eventName` set to `"Approval"`.
 */
export function useIerc20PermitApprovalEvent(
  config: Omit<
    UseContractEventConfig<typeof ierc20PermitABI, 'Approval'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: ierc20PermitABI,
    eventName: 'Approval',
    ...config,
  } as UseContractEventConfig<typeof ierc20PermitABI, 'Approval'>)
}

/**
 * Wraps __{@link useContractEvent}__ with `abi` set to __{@link ierc20PermitABI}__ and `eventName` set to `"Transfer"`.
 */
export function useIerc20PermitTransferEvent(
  config: Omit<
    UseContractEventConfig<typeof ierc20PermitABI, 'Transfer'>,
    'abi' | 'eventName'
  > = {} as any,
) {
  return useContractEvent({
    abi: ierc20PermitABI,
    eventName: 'Transfer',
    ...config,
  } as UseContractEventConfig<typeof ierc20PermitABI, 'Transfer'>)
}
